### ISSUE TITLE
[DEV] Overview of issues related to parametric and consolation

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/IncrementalInference.jl#558]
### Framework
Working on the parametric solution #468, I found it difficult in a few areas and tried to come up with a framework that the current implementation can be consolidated into.  The framework implemented in PR #468 should be seen as my proposal on:
1. Belief messages #459
2. Message channels #459
3. The BayesTree structure - Could only be partially implemented
    - Towards breaking tree dependence on Graphs.jl #525
    -  WIP Linear parametric solution #468
    - TreeClique index field and underlining graphs structure indexes #540
    - Also #551

Related: Potential improvements to manifolds and storage, but nothing done there #465 

### Parametric Solution 
WIP Linear parametric solution #468 merged without:
1. Calculate covariances for parametric tree solve #539
2. Parametric tree initialization #541
3. Manifold and non-linear
    - Wrapper for parametric factor evaluation #467

Related: build linear Gaussian chain rule utility function #466

### Dehann's Ticklist
The quick answer is I'm working on none of them.
- :x: not going to do
- :heavy_check_mark: done
- [x] Currently working on

Hi @Affie, I need some help understanding what you are doing at the moment please (a cheeky request) -- could you tick all that apply...  We need to stay a little synchronized here, you are moving quick with so many things! :-)
- [x] Writing issues (DF nice!)
- :heavy_check_mark: Paramatric proof of concept 2D linear? 
    - POC done with outstanding functions as listed above
- :heavy_check_mark:  Parametric PoC manifold (non-linear) improvement?
    - Used optim `project`/`retract` methods
- [ ] ~~Parametric integration with existing factor definitions --~~ (#467)
- [x] Parametric integration or improvements to current CSMC data containers?
- :heavy_check_mark: Parametric PoC using existing BayesTree?
     - POC done with outstanding functions as listed above
- :heavy_check_mark: Preparation on current Bayes tree so that we can slowly move away from Graphs.jl for the BayesTree specifically?
    - See above
- [x] Building a new MetaBayesTree (#609)? Blocking on #540
- [x] Standardizing message channels on the existing Bayes tree? Blocking on #459
- [x] Building a new message channels on the existing Bayes tree? Blocking on #459
- :x: Building separate message channels on a new Bayes tree that is not at all integrated with current Bayes tree? 
     - I hope that is not what I did
- :heavy_check_mark: Standardizing or incorporating new fields in existing Belief message types? Blocking on #459
- :heavy_check_mark: Building new message types that work on existing Bayes tree? Blocking on #459
- :x: Building new messages that only work on a new MetaBayesTree and not at all consolidated or integrated with existing code?
    - Again, I hope not 

Please list any other things below?
- [x]  #556

PS, if any of these items above are not consolidated, how and where are we going to consolidate them?

PSS, Please edit with sub-bullet if any of these items are already finished? 

PSSS, we may need to sync this a group a little and rather finish some items before starting new stuff.

**Comment by dehann** [comment]
As I understand the two most importing things you are blocking on me on are:
- [ ] How to do covariance calculation for Gaussian belief prop,
- [ ] Consolidation of the tree message Channels in Bayes tree.

**Comment by dehann** [comment]
Haha, thanks enjoyed the "state of the nation" theme!  Thanks this actually really helps a lot with scoping work on my side.  Lets work to clear this list of stuff before we start anything new?

**Comment by dehann** [comment]
CSM and ParametricCSM should be interchangeable, so that users can float between various Chapman-Kolmogorov solution strategies in development and use.

**Comment by Affie** [comment]
I'm closing this as the only remaining issue is captured in #467

**Comment by dehann** [comment]
Thanks @Affie, that was an major pile of work.  Thanks for all the effort!
