### ISSUE TITLE
Take! Clique State Machine Resolution

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/IncrementalInference.jl#989]
Overview of issues remaining in the take! CSM after consolidation
- [x] Marginalized Recycling #992
- [x] Marginalized Recycling Tests #992
- [x] Incremental Recycling #992
- [x] Incremental Recycling Tests #992
- [x] Check down Recycling
- [x] Improve Recycling Tests
- [x] Use correct clique colors and number
- [x] Upsolve only and test #991
- [x] Missed the CSM debugging functions added after branch 
    -   ✓timeout, ✓verbosefid=verbosefid, ✓housekeeping_cb=csmiter_cb, injectDelayBefore=injectDelayBefore

Tracked by own issues:
- CSM, downsolve only API w/ existing upsolved state #567 ~(also for upsolve)~ Added upsolve only
- Parent CSM should resolve sibling init order (if partials or similar) #954
- Consolidate btnd.solvableDims into LikelihoodMessage #910
- Cascaded down init?  part of #954
  - (just keeping this door open via `msg.solvableDims` based on previous experience).
